# .vale.ini
StylesPath = .github/vale/styles
MinAlertLevel = suggestion

# Folder-specific rules
# Ignore Jekyll YAML front matter
[_documentation/*.md]
BasedOnStyles = Vale, Microsoft
TokenIgnores = ^---(\n|.)*?---

[_docs_creation_APIs/*.md]
BasedOnStyles = Vale, Microsoft
TokenIgnores = ^---(\n|.)*?---

# Ignore build output and vendor folders
Ignored = _site/**, vendor/**, node_modules/**
