# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Global Docs API Service - Integration Guide
description: >- # this means to ignore newlines until "baseurl:"
  This is a document that I have created with sanitized text content to replicate a standard API Integration Guide. The main purpose of creating this site is to practise the various docs-as-code approaches with different static site generators and different deployment systems. This is created using a minimalistic Jekyll theme and GitHub Pages.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://AllAboutDocs.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Include Aviator’s folders in the build
include:
  - _pages
  - _posts
  - _data
  - _layouts
  - _includes
  - assets

# Build settings
collections:
  docs-creation-and-management-apis:
    output: true
    position_number: 1
  docs-update-via-lists-apis:
    output: true
    position_number: 2
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "docs-creation-and-management-apis"
    values:
      layout: "default"
      section: "docs"
  - scope:
      path: ""
      type: "docs-update-via-lists-apis"
    values:
      layout: "default"
      section: "docs"

# ======================================================
#  Aviator Theme Options (adjust as needed)
# ======================================================
aviator:
  banner:
    title: "API Integration Guide"
    subtitle: "Testing the Aviator Theme"
  #social:
  #github: "https://github.com/AllAboutDocs"
  #twitter: "https://twitter.com/your-twitter-handle"
  #linkedin: "https://linkedin.com/company/your-company"
# Exclude from processing.
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - package.json
  - package-lock.json
